version: '2.1'

services:
   php-cli:
      network_mode: bridge
      image: php:8.0-cli
      user: ${USER_ID}
      volumes:
         - .:/src
      working_dir: /src

   composer:
      network_mode: bridge
      image: composer:latest
      user: ${USER_ID}
      volumes:
         - .:/src
         - ${HOME}/.composer:/.composer
      working_dir: /src
      environment:
         - COMPOSER_CACHE_DIR=/.composer
         - COMPOSER_ALLOW_SUPERUSER=1

   semver:
      network_mode: bridge
      image: marcelocorreia/semver:latest
      user: ${USER_ID}
      volumes:
         - .:/src
      working_dir: /src
